name: qa_automation_integration_test_task
description: QA Automation test task.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 3.0.1
  email_validator: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: 2.1.2
  flutter_gherkin: 3.0.0-rc.9
  gherkin: 2.0.8
  flutter_lints: 1.0.0


flutter:
  uses-material-design: true
